# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


name: 10.0.$(Build.BuildId)
variables:
  version: 10.0.$(Build.BuildId)
 
stages:
  - stage: Continous_Integration
    displayName: Integração continua
    jobs:
      - job: Build
        variables:
          SolutionPath: src
          Solution: EntityFrameworkCoreChangeTracker.sln
        steps:
          - task: UseDotNet@2
            displayName: Instalando o .NET 10
            inputs:
              version: '10.x'
              packageType: sdk
              installationPath: $(Agent.ToolsDirectory)/dotnet

          - task: PowerShell@2
            displayName: Criando pacote com as bibliotecas
            inputs:
              targetType: 'inline'
              script: 'dotnet build $(solution) --no-incremental -c Release; dotnet pack $(solution) /p:Version=$(version) /p:PackageVersion=$(version) --include-symbols --include-source -c Release -o $(Build.StagingDirectory)/artifact/'
              pwsh: true
              workingDirectory: '$(SolutionPath)'

          - task: PublishBuildArtifacts@1
            displayName: "Publicando os artefatos no AzureDevOps"
            condition: and(succeeded(),or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.SourceBranch'], 'refs/heads/release')))
            inputs:
              name: artifact
              PathtoPublish: "$(Build.StagingDirectory)/artifact/"
              ArtifactName: artifact
